spring:
  application:
    name: ticketsystem

  datasource:
    url: jdbc:h2:mem:gesticket_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  h2:
    console:
      enabled: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081
  servlet:
    context-path: /api
